#!/usr/bin/env python3
"""Generate data/drafts/c1_vocabulary_exhaustive.csv for C1 exam prep (content only)."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "drafts" / "c1_vocabulary_exhaustive.csv"

# (section, german, english)
ENTRIES: list[tuple[str, str, str]] = [
    # ── 1. Schreiben: Erörterung & Stellungnahme — Einleitung ──
    ("1. Schreiben — Einleitung", "In letzter Zeit wird intensiv darüber diskutiert, ob", "Recently there has been intense debate about whether"),
    ("1. Schreiben — Einleitung", "Angesichts der aktuellen Entwicklungen stellt sich die Frage, ob", "Given current developments, the question arises whether"),
    ("1. Schreiben — Einleitung", "Ein kontroverses Thema, das in der Öffentlichkeit viel Beachtung findet, ist", "A controversial topic that receives much public attention is"),
    ("1. Schreiben — Einleitung", "Immer häufiger wird darüber nachgedacht, ob", "People increasingly wonder whether"),
    ("1. Schreiben — Einleitung", "Vor dem Hintergrund globaler Herausforderungen gewinnt die Frage an Bedeutung, ob", "Against the backdrop of global challenges, the question gains importance whether"),
    ("1. Schreiben — Einleitung", "Die Diskussion um … hat in den vergangenen Jahren an Intensität zugenommen", "The debate about … has intensified in recent years"),
    ("1. Schreiben — Einleitung", "Es ist unbestritten, dass … eine zentrale Rolle in unserer Gesellschaft spielt", "It is undisputed that … plays a central role in our society"),
    ("1. Schreiben — Einleitung", "Zunehmend stellen sich Bürgerinnen und Bürger die Frage, inwieweit", "Citizens increasingly ask themselves to what extent"),
    ("1. Schreiben — Einleitung", "Ein Thema, das polarisiert und unterschiedliche Standpunkte hervorruft, ist", "A topic that polarizes and provokes different views is"),
    ("1. Schreiben — Einleitung", "Die vorliegende Erörterung befasst sich mit der Frage, ob", "This essay examines the question of whether"),
    ("1. Schreiben — Einleitung", "die Aktualität des Themas", "the topicality of the subject"),
    ("1. Schreiben — Einleitung", "die Problematik", "the problem / issue"),
    ("1. Schreiben — Einleitung", "der Sachverhalt", "the facts / state of affairs"),
    ("1. Schreiben — Einleitung", "die Ausgangslage", "the initial situation"),
    ("1. Schreiben — Einleitung", "der Anlass", "the occasion / reason"),
    # ── 2. Schreiben — Argumentation ──
    ("2. Schreiben — Argumentation", "Ein wesentlicher Aspekt, der für … spricht, ist", "An essential aspect in favour of … is"),
    ("2. Schreiben — Argumentation", "Ein wesentlicher Aspekt, der gegen … spricht, ist", "An essential aspect against … is"),
    ("2. Schreiben — Argumentation", "Dies lässt sich darauf zurückführen, dass", "This can be attributed to the fact that"),
    ("2. Schreiben — Argumentation", "Ein überzeugendes Argument dafür ist, dass", "A convincing argument for this is that"),
    ("2. Schreiben — Argumentation", "Daraus folgt, dass", "It follows from this that"),
    ("2. Schreiben — Argumentation", "Es lässt sich nicht bestreiten, dass", "It cannot be denied that"),
    ("2. Schreiben — Argumentation", "Es ist erwiesen, dass", "It has been proven that"),
    ("2. Schreiben — Argumentation", "Die Evidenz spricht dafür, dass", "The evidence suggests that"),
    ("2. Schreiben — Argumentation", "Ein weiterer relevanter Punkt ist", "Another relevant point is"),
    ("2. Schreiben — Argumentation", "Darüber hinaus ist zu berücksichtigen, dass", "Furthermore, it should be considered that"),
    ("2. Schreiben — Argumentation", "Nicht zuletzt spielt … eine entscheidende Rolle", "Last but not least, … plays a decisive role"),
    ("2. Schreiben — Argumentation", "Dies verdeutlicht, dass", "This illustrates that"),
    ("2. Schreiben — Argumentation", "Dies unterstreicht die Bedeutung von", "This underscores the importance of"),
    ("2. Schreiben — Argumentation", "Die Tragweite dieser Entwicklung", "the far-reaching implications of this development"),
    ("2. Schreiben — Argumentation", "die Konsequenzen", "the consequences"),
    ("2. Schreiben — Argumentation", "die Auswirkungen", "the effects / impacts"),
    ("2. Schreiben — Argumentation", "die Begründung", "the justification / reasoning"),
    ("2. Schreiben — Argumentation", "die These", "the thesis"),
    ("2. Schreiben — Argumentation", "die Belegführung", "the presentation of evidence"),
    ("2. Schreiben — Argumentation", "belegen", "to substantiate / prove"),
    ("2. Schreiben — Argumentation", "untermauern", "to underpin / support"),
    ("2. Schreiben — Argumentation", "begründen", "to justify"),
    ("2. Schreiben — Argumentation", "verdeutlichen", "to clarify / illustrate"),
    ("2. Schreiben — Argumentation", "herausstellen", "to emphasize / highlight"),
    # ── 3. Schreiben — Gegenargumente ──
    ("3. Schreiben — Gegenargumente", "Zwar ist es richtig, dass …, jedoch darf nicht außer Acht gelassen werden, dass", "Admittedly …, however, it must not be overlooked that"),
    ("3. Schreiben — Gegenargumente", "Gegner dieser Auffassung führen an, dass", "Opponents of this view argue that"),
    ("3. Schreiben — Gegenargumente", "Kritiker wenden ein, dass", "Critics object that"),
    ("3. Schreiben — Gegenargumente", "Demgegenüber steht, dass", "In contrast to this stands the fact that"),
    ("3. Schreiben — Gegenargumente", "Andererseits ist jedoch zu bedenken, dass", "On the other hand, however, it should be considered that"),
    ("3. Schreiben — Gegenargumente", "Man könnte entgegnen, dass", "One could counter that"),
    ("3. Schreiben — Gegenargumente", "Diesem Argument lässt sich entgegenhalten, dass", "This argument can be countered by the fact that"),
    ("3. Schreiben — Gegenargumente", "Trotz dieser Bedenken überwiegen die Vorteile", "Despite these concerns, the advantages outweigh"),
    ("3. Schreiben — Gegenargumente", "Ein Einwand gegen … wäre, dass", "An objection to … would be that"),
    ("3. Schreiben — Gegenargumente", "Das Gegenargument", "the counterargument"),
    ("3. Schreiben — Gegenargumente", "die Einwände entkräften", "to refute the objections"),
    ("3. Schreiben — Gegenargumente", "widerlegen", "to refute"),
    ("3. Schreiben — Gegenargumente", "relativieren", "to put into perspective / relativize"),
    ("3. Schreiben — Gegenargumente", "abwägen", "to weigh up"),
    ("3. Schreiben — Gegenargumente", "die Abwägung", "the weighing of pros and cons"),
    # ── 4. Schreiben — Schluss ──
    ("4. Schreiben — Schluss", "Zusammenfassend lässt sich festhalten, dass", "In summary, it can be stated that"),
    ("4. Schreiben — Schluss", "Abschließend kann konstatiert werden, dass", "In conclusion, it can be affirmed that"),
    ("4. Schreiben — Schluss", "Meines Erachtens überwiegen die Vorteile, da", "In my view, the advantages outweigh, because"),
    ("4. Schreiben — Schluss", "Meines Erachtens überwiegen die Nachteile, da", "In my view, the disadvantages outweigh, because"),
    ("4. Schreiben — Schluss", "Alles in allem spricht viel dafür, dass", "All in all, there is much to suggest that"),
    ("4. Schreiben — Schluss", "Unterm Strich lässt sich sagen, dass", "Bottom line, one can say that"),
    ("4. Schreiben — Schluss", "Letztlich hängt die Beurteilung davon ab, inwieweit", "Ultimately, the assessment depends on the extent to which"),
    ("4. Schreiben — Schluss", "Ich komme zu dem Schluss, dass", "I conclude that"),
    ("4. Schreiben — Schluss", "Die vorliegende Analyse zeigt, dass", "The present analysis shows that"),
    ("4. Schreiben — Schluss", "das Fazit ziehen", "to draw a conclusion"),
    ("4. Schreiben — Schluss", "resümieren", "to summarize"),
    ("4. Schreiben — Schluss", "die Schlussfolgerung", "the conclusion"),
    ("4. Schreiben — Schluss", "die Gesamtbewertung", "the overall assessment"),
    # ── 5. Konnektoren & Satzadverbien (C1) ──
    ("5. Konnektoren (C1)", "dennoch", "nevertheless"),
    ("5. Konnektoren (C1)", "gleichwohl", "nevertheless / albeit (formal)"),
    ("5. Konnektoren (C1)", "folglich", "consequently"),
    ("5. Konnektoren (C1)", "demzufolge", "accordingly / hence"),
    ("5. Konnektoren (C1)", "insofern", "insofar as"),
    ("5. Konnektoren (C1)", "insofern als", "insofar as"),
    ("5. Konnektoren (C1)", "inwiefern", "to what extent"),
    ("5. Konnektoren (C1)", "inwieweit", "to what extent"),
    ("5. Konnektoren (C1)", "des Weiteren", "furthermore"),
    ("5. Konnektoren (C1)", "darüber hinaus", "beyond that / moreover"),
    ("5. Konnektoren (C1)", "zudem", "in addition"),
    ("5. Konnektoren (C1)", "überdies", "moreover / besides"),
    ("5. Konnektoren (C1)", "hingegen", "whereas / on the other hand"),
    ("5. Konnektoren (C1)", "demgegenüber", "in contrast to that"),
    ("5. Konnektoren (C1)", "demgegenüber steht", "in contrast stands"),
    ("5. Konnektoren (C1)", "während hingegen", "whereas on the other hand"),
    ("5. Konnektoren (C1)", "sofern", "provided that"),
    ("5. Konnektoren (C1)", "soweit", "insofar as / as far as"),
    ("5. Konnektoren (C1)", "obgleich", "although (formal)"),
    ("5. Konnektoren (C1)", "obschon", "although (literary/formal)"),
    ("5. Konnektoren (C1)", "zumal", "especially since / all the more because"),
    ("5. Konnektoren (C1)", "insofern als", "in that / since"),
    ("5. Konnektoren (C1)", "mit anderen Worten", "in other words"),
    ("5. Konnektoren (C1)", "das heißt", "that is / i.e."),
    ("5. Konnektoren (C1)", "beispielsweise", "for example"),
    ("5. Konnektoren (C1)", "namentlich", "namely"),
    ("5. Konnektoren (C1)", "insbesondere", "in particular"),
    ("5. Konnektoren (C1)", "vor allem", "above all"),
    ("5. Konnektoren (C1)", "in erster Linie", "primarily / first and foremost"),
    ("5. Konnektoren (C1)", "grundsätzlich", "in principle / fundamentally"),
    ("5. Konnektoren (C1)", "grundsätzlich gesprochen", "fundamentally speaking"),
    ("5. Konnektoren (C1)", "im Grunde genommen", "basically"),
    ("5. Konnektoren (C1)", "letztendlich", "ultimately"),
    ("5. Konnektoren (C1)", "schließlich", "finally / after all"),
    ("5. Konnektoren (C1)", "in der Folge", "as a consequence"),
    ("5. Konnektoren (C1)", "in der Konsequenz", "as a consequence"),
    ("5. Konnektoren (C1)", "somit", "thus / therefore"),
    ("5. Konnektoren (C1)", "mithin", "thus / hence (formal)"),
    ("5. Konnektoren (C1)", "demnach", "accordingly / therefore"),
    ("5. Konnektoren (C1)", "infolgedessen", "as a result"),
    ("5. Konnektoren (C1)", "demzufolge", "accordingly"),
    # ── 6. Meinung & Bewertung ──
    ("6. Meinung & Bewertung", "Meiner Meinung nach", "In my opinion"),
    ("6. Meinung & Bewertung", "Meines Erachtens", "In my view"),
    ("6. Meinung & Bewertung", "Ich bin der Ansicht, dass", "I am of the opinion that"),
    ("6. Meinung & Bewertung", "Ich vertrete die Auffassung, dass", "I hold the view that"),
    ("6. Meinung & Bewertung", "Es ist meine feste Überzeugung, dass", "It is my firm conviction that"),
    ("6. Meinung & Bewertung", "Ich halte es für wünschenswert, dass", "I consider it desirable that"),
    ("6. Meinung & Bewertung", "Ich halte es für problematisch, dass", "I consider it problematic that"),
    ("6. Meinung & Bewertung", "Es lässt sich nicht leugnen, dass", "It cannot be denied that"),
    ("6. Meinung & Bewertung", "Es steht außer Frage, dass", "There is no question that"),
    ("6. Meinung & Bewertung", "Es ist zweifellos", "It is undoubtedly"),
    ("6. Meinung & Bewertung", "Es ist fraglich, ob", "It is questionable whether"),
    ("6. Meinung & Bewertung", "Es bleibt abzuwarten, ob", "It remains to be seen whether"),
    ("6. Meinung & Bewertung", "die Einschätzung", "the assessment / estimate"),
    ("6. Meinung & Bewertung", "die Bewertung", "the evaluation"),
    ("6. Meinung & Bewertung", "die Kritik", "the criticism"),
    ("6. Meinung & Bewertung", "kritisch hinterfragen", "to question critically"),
    ("6. Meinung & Bewertung", "differenziert betrachten", "to view in a differentiated way"),
    ("6. Meinung & Bewertung", "vorteilhaft", "advantageous"),
    ("6. Meinung & Bewertung", "nachteilig", "disadvantageous"),
    ("6. Meinung & Bewertung", "ausschlaggebend", "decisive"),
    ("6. Meinung & Bewertung", "maßgeblich", "decisive / significant"),
    ("6. Meinung & Bewertung", "bedeutsam", "significant"),
    ("6. Meinung & Bewertung", "relevant", "relevant"),
    ("6. Meinung & Bewertung", "fragwürdig", "questionable"),
    ("6. Meinung & Bewertung", "unbestritten", "undisputed"),
    ("6. Meinung & Bewertung", "umstritten", "controversial"),
    # ── 7. Nominalstil (C1) ──
    ("7. Nominalstil", "die Durchführung", "the implementation / carrying out"),
    ("7. Nominalstil", "die Feststellung", "the finding / determination"),
    ("7. Nominalstil", "die Berücksichtigung", "the consideration / taking into account"),
    ("7. Nominalstil", "die Verbesserung", "the improvement"),
    ("7. Nominalstil", "die Verschlechterung", "the deterioration"),
    ("7. Nominalstil", "die Steigerung", "the increase"),
    ("7. Nominalstil", "die Senkung", "the reduction / lowering"),
    ("7. Nominalstil", "die Förderung", "the promotion / support"),
    ("7. Nominalstil", "die Unterstützung", "the support"),
    ("7. Nominalstil", "die Einschränkung", "the restriction"),
    ("7. Nominalstil", "die Ausweitung", "the expansion"),
    ("7. Nominalstil", "die Verstärkung", "the strengthening"),
    ("7. Nominalstil", "die Abschaffung", "the abolition"),
    ("7. Nominalstil", "die Einführung", "the introduction"),
    ("7. Nominalstil", "die Umsetzung", "the implementation"),
    ("7. Nominalstil", "die Gewährleistung", "the guarantee / ensuring"),
    ("7. Nominalstil", "die Sicherstellung", "the ensuring / safeguarding"),
    ("7. Nominalstil", "die Beeinträchtigung", "the impairment"),
    ("7. Nominalstil", "die Beeinflussung", "the influence"),
    ("7. Nominalstil", "die Wahrnehmung", "the perception"),
    ("7. Nominalstil", "die Kenntnisnahme", "the taking note of"),
    ("7. Nominalstil", "zur Verfügung stellen", "to make available"),
    ("7. Nominalstil", "in Betracht ziehen", "to take into consideration"),
    ("7. Nominalstil", "zur Sprache bringen", "to bring up / raise (a topic)"),
    ("7. Nominalstil", "in Frage stellen", "to call into question"),
    ("7. Nominalstil", "zur Debatte stehen", "to be up for debate"),
    ("7. Nominalstil", "Anklage finden", "to find approval / acceptance"),
    ("7. Nominalstil", "Kritik erfahren", "to receive criticism"),
    ("7. Nominalstil", "Beachtung finden", "to receive attention"),
    # ── 8. Gesellschaft & Demokratie ──
    ("8. Gesellschaft & Demokratie", "die Demokratie", "democracy"),
    ("8. Gesellschaft & Demokratie", "die Zivilgesellschaft", "civil society"),
    ("8. Gesellschaft & Demokratie", "die Bürgerrechte", "civil rights"),
    ("8. Gesellschaft & Demokratie", "die Menschenrechte", "human rights"),
    ("8. Gesellschaft & Demokratie", "die Meinungsfreiheit", "freedom of opinion"),
    ("8. Gesellschaft & Demokratie", "die Pressefreiheit", "freedom of the press"),
    ("8. Gesellschaft & Demokratie", "die Gewaltenteilung", "separation of powers"),
    ("8. Gesellschaft & Demokratie", "die Opposition", "the opposition"),
    ("8. Gesellschaft & Demokratie", "die Regierung", "the government"),
    ("8. Gesellschaft & Demokratie", "das Parlament", "parliament"),
    ("8. Gesellschaft & Demokratie", "der Bundestag", "German federal parliament"),
    ("8. Gesellschaft & Demokratie", "der Bundesrat", "German federal council"),
    ("8. Gesellschaft & Demokratie", "die Wahl", "the election"),
    ("8. Gesellschaft & Demokratie", "die Wahlbeteiligung", "voter turnout"),
    ("8. Gesellschaft & Demokratie", "die Stimmabgabe", "casting a vote"),
    ("8. Gesellschaft & Demokratie", "das Wahlrecht", "the right to vote"),
    ("8. Gesellschaft & Demokratie", "die Volksvertretung", "parliament / people's representation"),
    ("8. Gesellschaft & Demokratie", "die Partei", "the party"),
    ("8. Gesellschaft & Demokratie", "die Koalition", "the coalition"),
    ("8. Gesellschaft & Demokratie", "die Opposition", "the opposition"),
    ("8. Gesellschaft & Demokratie", "der Politiker / die Politikerin", "politician"),
    ("8. Gesellschaft & Demokratie", "der Wähler / die Wählerin", "voter"),
    ("8. Gesellschaft & Demokratie", "die Öffentlichkeit", "the public"),
    ("8. Gesellschaft & Demokratie", "die gesellschaftliche Debatte", "public debate"),
    ("8. Gesellschaft & Demokratie", "die politische Kultur", "political culture"),
    ("8. Gesellschaft & Demokratie", "das politische System", "political system"),
    ("8. Gesellschaft & Demokratie", "die politische Partizipation", "political participation"),
    ("8. Gesellschaft & Demokratie", "die Bürgerbeteiligung", "citizen participation"),
    ("8. Gesellschaft & Demokratie", "die Lobby", "lobby"),
    ("8. Gesellschaft & Demokratie", "der Lobbyismus", "lobbyism"),
    ("8. Gesellschaft & Demokratie", "die Korruption", "corruption"),
    ("8. Gesellschaft & Demokratie", "die Transparenz", "transparency"),
    ("8. Gesellschaft & Demokratie", "die Rechenschaftspflicht", "accountability"),
    ("8. Gesellschaft & Demokratie", "demokratisch", "democratic"),
    ("8. Gesellschaft & Demokratie", "bürgernah", "close to citizens"),
    ("8. Gesellschaft & Demokratie", "repräsentativ", "representative"),
    # ── 9. Politik & Staat ──
    ("9. Politik & Staat", "die Politik", "politics / policy"),
    ("9. Politik & Staat", "die Gesetzgebung", "legislation"),
    ("9. Politik & Staat", "das Gesetz", "the law"),
    ("9. Politik & Staat", "die Verfassung", "the constitution"),
    ("9. Politik & Staat", "das Grundgesetz", "Basic Law (German constitution)"),
    ("9. Politik & Staat", "die Reform", "the reform"),
    ("9. Politik & Staat", "die Regulierung", "regulation"),
    ("9. Politik & Staat", "die Deregulierung", "deregulation"),
    ("9. Politik & Staat", "die Subvention", "subsidy"),
    ("9. Politik & Staat", "die Steuer", "tax"),
    ("9. Politik & Staat", "die Steuerpolitik", "tax policy"),
    ("9. Politik & Staat", "der Haushalt", "budget"),
    ("9. Politik & Staat", "die Staatsverschuldung", "public debt"),
    ("9. Politik & Staat", "die Staatsquote", "government spending ratio"),
    ("9. Politik & Staat", "die Innenpolitik", "domestic policy"),
    ("9. Politik & Staat", "die Außenpolitik", "foreign policy"),
    ("9. Politik & Staat", "die Sicherheitspolitik", "security policy"),
    ("9. Politik & Staat", "die Sozialpolitik", "social policy"),
    ("9. Politik & Staat", "die Bildungspolitik", "education policy"),
    ("9. Politik & Staat", "die Wirtschaftspolitik", "economic policy"),
    ("9. Politik & Staat", "die Gesundheitspolitik", "health policy"),
    ("9. Politik & Staat", "der Staat", "the state"),
    ("9. Politik & Staat", "die Behörde", "authority / agency"),
    ("9. Politik & Staat", "die Verwaltung", "administration"),
    ("9. Politik & Staat", "die Bürokratie", "bureaucracy"),
    ("9. Politik & Staat", "der Minister / die Ministerin", "minister"),
    ("9. Politik & Staat", "das Ministerium", "ministry"),
    ("9. Politik & Staat", "der Kanzler / die Kanzlerin", "chancellor"),
    ("9. Politik & Staat", "der Bundespräsident / die Bundespräsidentin", "Federal President"),
    ("9. Politik & Staat", "verabschieden (Gesetz)", "to pass (a law)"),
    ("9. Politik & Staat", "in Kraft treten", "to come into force"),
    ("9. Politik & Staat", "regieren", "to govern"),
    ("9. Politik & Staat", "regulieren", "to regulate"),
    ("9. Politik & Staat", "subventionieren", "to subsidize"),
    ("9. Politik & Staat", "reformieren", "to reform"),
    # ── 10. Recht & Gerechtigkeit ──
    ("10. Recht & Gerechtigkeit", "das Recht", "the law / right"),
    ("10. Recht & Gerechtigkeit", "die Gerechtigkeit", "justice / fairness"),
    ("10. Recht & Gerechtigkeit", "die Ungerechtigkeit", "injustice"),
    ("10. Recht & Gerechtigkeit", "die Gleichheit", "equality"),
    ("10. Recht & Gerechtigkeit", "die Chancengleichheit", "equal opportunity"),
    ("10. Recht & Gerechtigkeit", "die Diskriminierung", "discrimination"),
    ("10. Recht & Gerechtigkeit", "die Benachteiligung", "disadvantage / discrimination"),
    ("10. Recht & Gerechtigkeit", "der Rechtsstaat", "constitutional state / rule of law"),
    ("10. Recht & Gerechtigkeit", "das Gericht", "court"),
    ("10. Recht & Gerechtigkeit", "der Richter / die Richterin", "judge"),
    ("10. Recht & Gerechtigkeit", "der Anwalt / die Anwältin", "lawyer"),
    ("10. Recht & Gerechtigkeit", "die Klage", "lawsuit / complaint"),
    ("10. Recht & Gerechtigkeit", "das Urteil", "verdict / judgment"),
    ("10. Recht & Gerechtigkeit", "die Strafe", "punishment / penalty"),
    ("10. Recht & Gerechtigkeit", "die Geldstrafe", "fine"),
    ("10. Recht & Gerechtigkeit", "die Freiheitsstrafe", "prison sentence"),
    ("10. Recht & Gerechtigkeit", "die Verurteilung", "conviction"),
    ("10. Recht & Gerechtigkeit", "der Anklagepunkt", "charge / count"),
    ("10. Recht & Gerechtigkeit", "die Verteidigung", "defence"),
    ("10. Recht & Gerechtigkeit", "die Zeugenaussage", "witness testimony"),
    ("10. Recht & Gerechtigkeit", "die Beweisführung", "presentation of evidence"),
    ("10. Recht & Gerechtigkeit", "rechtswidrig", "unlawful"),
    ("10. Recht & Gerechtigkeit", "rechtskräftig", "legally binding"),
    ("10. Recht & Gerechtigkeit", "verklagen", "to sue"),
    ("10. Recht & Gerechtigkeit", "verurteilen", "to convict / sentence"),
    ("10. Recht & Gerechtigkeit", "freisprechen", "to acquit"),
    ("10. Recht & Gerechtigkeit", "die Rechtsprechung", "jurisprudence / case law"),
    ("10. Recht & Gerechtigkeit", "die Gesetzgebungskompetenz", "legislative authority"),
    # ── 11. Wirtschaft & Finanzen ──
    ("11. Wirtschaft & Finanzen", "die Wirtschaft", "the economy"),
    ("11. Wirtschaft & Finanzen", "das Wirtschaftswachstum", "economic growth"),
    ("11. Wirtschaft & Finanzen", "die Rezession", "recession"),
    ("11. Wirtschaft & Finanzen", "die Inflation", "inflation"),
    ("11. Wirtschaft & Finanzen", "die Deflation", "deflation"),
    ("11. Wirtschaft & Finanzen", "die Konjunktur", "economic cycle / business climate"),
    ("11. Wirtschaft & Finanzen", "die Arbeitslosigkeit", "unemployment"),
    ("11. Wirtschaft & Finanzen", "die Arbeitslosenquote", "unemployment rate"),
    ("11. Wirtschaft & Finanzen", "die Investition", "investment"),
    ("11. Wirtschaft & Finanzen", "die Ausgaben", "expenditure"),
    ("11. Wirtschaft & Finanzen", "die Einnahmen", "revenue / income"),
    ("11. Wirtschaft & Finanzen", "der Gewinn", "profit"),
    ("11. Wirtschaft & Finanzen", "der Verlust", "loss"),
    ("11. Wirtschaft & Finanzen", "der Umsatz", "turnover / revenue"),
    ("11. Wirtschaft & Finanzen", "der Markt", "market"),
    ("11. Wirtschaft & Finanzen", "der Wettbewerb", "competition"),
    ("11. Wirtschaft & Finanzen", "das Monopol", "monopoly"),
    ("11. Wirtschaft & Finanzen", "das Oligopol", "oligopoly"),
    ("11. Wirtschaft & Finanzen", "die Nachfrage", "demand"),
    ("11. Wirtschaft & Finanzen", "das Angebot", "supply"),
    ("11. Wirtschaft & Finanzen", "der Aktienkurs", "share price"),
    ("11. Wirtschaft & Finanzen", "die Börse", "stock exchange"),
    ("11. Wirtschaft & Finanzen", "die Aktie", "share / stock"),
    ("11. Wirtschaft & Finanzen", "die Anleihe", "bond"),
    ("11. Wirtschaft & Finanzen", "die Zinsen", "interest (rate)"),
    ("11. Wirtschaft & Finanzen", "die Währung", "currency"),
    ("11. Wirtschaft & Finanzen", "der Wechselkurs", "exchange rate"),
    ("11. Wirtschaft & Finanzen", "die Globalisierung", "globalization"),
    ("11. Wirtschaft & Finanzen", "der Handel", "trade"),
    ("11. Wirtschaft & Finanzen", "der Export", "export"),
    ("11. Wirtschaft & Finanzen", "der Import", "import"),
    ("11. Wirtschaft & Finanzen", "das Handelsdefizit", "trade deficit"),
    ("11. Wirtschaft & Finanzen", "das Bruttoinlandsprodukt (BIP)", "gross domestic product (GDP)"),
    ("11. Wirtschaft & Finanzen", "die Wirtschaftskrise", "economic crisis"),
    ("11. Wirtschaft & Finanzen", "die Finanzkrise", "financial crisis"),
    ("11. Wirtschaft & Finanzen", "die Staatsverschuldung", "public debt"),
    ("11. Wirtschaft & Finanzen", "investieren", "to invest"),
    ("11. Wirtschaft & Finanzen", "finanzieren", "to finance"),
    ("11. Wirtschaft & Finanzen", "subventionieren", "to subsidize"),
    ("11. Wirtschaft & Finanzen", "privatisieren", "to privatize"),
    ("11. Wirtschaft & Finanzen", "verstaatlichen", "to nationalize"),
    ("11. Wirtschaft & Finanzen", "florieren", "to flourish / thrive"),
    ("11. Wirtschaft & Finanzen", "stagnieren", "to stagnate"),
    # ── 12. Arbeit & Arbeitswelt ──
    ("12. Arbeit & Arbeitswelt", "die Arbeitswelt", "world of work"),
    ("12. Arbeit & Arbeitswelt", "der Arbeitsmarkt", "labour market"),
    ("12. Arbeit & Arbeitswelt", "die Arbeitsbedingungen", "working conditions"),
    ("12. Arbeit & Arbeitswelt", "die Arbeitszeit", "working hours"),
    ("12. Arbeit & Arbeitswelt", "die Überstunden", "overtime"),
    ("12. Arbeit & Arbeitswelt", "die Gleitzeit", "flexible hours"),
    ("12. Arbeit & Arbeitswelt", "das Homeoffice", "working from home"),
    ("12. Arbeit & Arbeitswelt", "die Telearbeit", "remote work"),
    ("12. Arbeit & Arbeitswelt", "die Work-Life-Balance", "work-life balance"),
    ("12. Arbeit & Arbeitswelt", "der Burnout", "burnout"),
    ("12. Arbeit & Arbeitswelt", "die Erschöpfung", "exhaustion"),
    ("12. Arbeit & Arbeitswelt", "die Kündigung", "termination / notice"),
    ("12. Arbeit & Arbeitswelt", "die Entlassung", "dismissal"),
    ("12. Arbeit & Arbeitswelt", "die Kündigungsfrist", "notice period"),
    ("12. Arbeit & Arbeitswelt", "der Tarifvertrag", "collective agreement"),
    ("12. Arbeit & Arbeitswelt", "die Gewerkschaft", "trade union"),
    ("12. Arbeit & Arbeitswelt", "der Streik", "strike"),
    ("12. Arbeit & Arbeitswelt", "die Verhandlung", "negotiation"),
    ("12. Arbeit & Arbeitswelt", "die Einstellung", "hiring / employment"),
    ("12. Arbeit & Arbeitswelt", "die Bewerbung", "job application"),
    ("12. Arbeit & Arbeitswelt", "das Vorstellungsgespräch", "job interview"),
    ("12. Arbeit & Arbeitswelt", "der Lebenslauf", "CV / résumé"),
    ("12. Arbeit & Arbeitswelt", "die Qualifikation", "qualification"),
    ("12. Arbeit & Arbeitswelt", "die Weiterbildung", "continuing education"),
    ("12. Arbeit & Arbeitswelt", "die Fortbildung", "professional development"),
    ("12. Arbeit & Arbeitswelt", "die Fachkraft", "skilled worker"),
    ("12. Arbeit & Arbeitswelt", "der Fachkräftemangel", "shortage of skilled workers"),
    ("12. Arbeit & Arbeitswelt", "die Digitalisierung der Arbeit", "digitalization of work"),
    ("12. Arbeit & Arbeitswelt", "die Automatisierung", "automation"),
    ("12. Arbeit & Arbeitswelt", "die Zukunft der Arbeit", "future of work"),
    ("12. Arbeit & Arbeitswelt", "der Mindestlohn", "minimum wage"),
    ("12. Arbeit & Arbeitswelt", "die Lohnerhöhung", "pay rise"),
    ("12. Arbeit & Arbeitswelt", "die Gehaltsverhandlung", "salary negotiation"),
    ("12. Arbeit & Arbeitswelt", "einstellen", "to hire"),
    ("12. Arbeit & Arbeitswelt", "entlassen", "to dismiss / fire"),
    ("12. Arbeit & Arbeitswelt", "kündigen", "to resign / terminate"),
    ("12. Arbeit & Arbeitswelt", "sich bewerben", "to apply (for a job)"),
    ("12. Arbeit & Arbeitswelt", "verhandeln", "to negotiate"),
    # ── 13. Bildung & Wissenschaft ──
    ("13. Bildung & Wissenschaft", "die Bildung", "education"),
    ("13. Bildung & Wissenschaft", "das Bildungssystem", "education system"),
    ("13. Bildung & Wissenschaft", "die Hochschule", "university / college"),
    ("13. Bildung & Wissenschaft", "die Universität", "university"),
    ("13. Bildung & Wissenschaft", "die Forschung", "research"),
    ("13. Bildung & Wissenschaft", "die Wissenschaft", "science / academia"),
    ("13. Bildung & Wissenschaft", "der Wissenschaftler / die Wissenschaftlerin", "scientist / researcher"),
    ("13. Bildung & Wissenschaft", "die Dissertation", "doctoral thesis"),
    ("13. Bildung & Wissenschaft", "die Promotion", "doctorate / PhD"),
    ("13. Bildung & Wissenschaft", "die Habilitation", "habilitation (post-doctoral qualification)"),
    ("13. Bildung & Wissenschaft", "die Studiengebühren", "tuition fees"),
    ("13. Bildung & Wissenschaft", "das Stipendium", "scholarship"),
    ("13. Bildung & Wissenschaft", "die Zulassungsvoraussetzung", "admission requirement"),
    ("13. Bildung & Wissenschaft", "die Einschreibung", "enrolment"),
    ("13. Bildung & Wissenschaft", "das Semester", "semester"),
    ("13. Bildung & Wissenschaft", "die Vorlesung", "lecture"),
    ("13. Bildung & Wissenschaft", "das Seminar", "seminar"),
    ("13. Bildung & Wissenschaft", "die Prüfung", "exam"),
    ("13. Bildung & Wissenschaft", "die Abschlussprüfung", "final exam"),
    ("13. Bildung & Wissenschaft", "der Abschluss", "degree / qualification"),
    ("13. Bildung & Wissenschaft", "der Bachelor", "bachelor's degree"),
    ("13. Bildung & Wissenschaft", "der Master", "master's degree"),
    ("13. Bildung & Wissenschaft", "der Doktortitel", "doctorate"),
    ("13. Bildung & Wissenschaft", "die Chancengleichheit im Bildungswesen", "equal opportunity in education"),
    ("13. Bildung & Wissenschaft", "die Bildungsgerechtigkeit", "educational equity"),
    ("13. Bildung & Wissenschaft", "die Bildungsreform", "education reform"),
    ("13. Bildung & Wissenschaft", "die Kompetenz", "competence / skill"),
    ("13. Bildung & Wissenschaft", "die Fachkompetenz", "subject expertise"),
    ("13. Bildung & Wissenschaft", "die Methodenkompetenz", "methodological competence"),
    ("13. Bildung & Wissenschaft", "akademisch", "academic"),
    ("13. Bildung & Wissenschaft", "wissenschaftlich", "scientific"),
    ("13. Bildung & Wissenschaft", "promovieren", "to do a doctorate"),
    ("13. Bildung & Wissenschaft", "forschen", "to do research"),
    ("13. Bildung & Wissenschaft", "lehren", "to teach"),
    # ── 14. Forschung & Akademia ──
    ("14. Forschung & Akademia", "die Studie", "study (research)"),
    ("14. Forschung & Akademia", "die Erhebung", "survey / data collection"),
    ("14. Forschung & Akademia", "die Statistik", "statistics"),
    ("14. Forschung & Akademia", "die Datenanalyse", "data analysis"),
    ("14. Forschung & Akademia", "die Hypothese", "hypothesis"),
    ("14. Forschung & Akademia", "die These", "thesis"),
    ("14. Forschung & Akademia", "die Methode", "method"),
    ("14. Forschung & Akademia", "die Methodik", "methodology"),
    ("14. Forschung & Akademia", "das Experiment", "experiment"),
    ("14. Forschung & Akademia", "die Erkenntnis", "finding / insight"),
    ("14. Forschung & Akademia", "das Ergebnis", "result"),
    ("14. Forschung & Akademia", "die Publikation", "publication"),
    ("14. Forschung & Akademia", "die Fachzeitschrift", "specialist journal"),
    ("14. Forschung & Akademia", "die Peer-Review", "peer review"),
    ("14. Forschung & Akademia", "die Zitation", "citation"),
    ("14. Forschung & Akademia", "die Quellenangabe", "source reference"),
    ("14. Forschung & Akademia", "die Literaturübersicht", "literature review"),
    ("14. Forschung & Akademia", "die Forschungsfrage", "research question"),
    ("14. Forschung & Akademia", "die Forschungslücke", "research gap"),
    ("14. Forschung & Akademia", "die Validität", "validity"),
    ("14. Forschung & Akademia", "die Reliabilität", "reliability"),
    ("14. Forschung & Akademia", "empirisch", "empirical"),
    ("14. Forschung & Akademia", "theoretisch", "theoretical"),
    ("14. Forschung & Akademia", "hypothetisch", "hypothetical"),
    ("14. Forschung & Akademia", "belegen", "to prove / substantiate"),
    ("14. Forschung & Akademia", "verifizieren", "to verify"),
    ("14. Forschung & Akademia", "widerlegen", "to refute"),
    ("14. Forschung & Akademia", "analysieren", "to analyse"),
    ("14. Forschung & Akademia", "interpretieren", "to interpret"),
    ("14. Forschung & Akademia", "veröffentlichen", "to publish"),
    # ── 15. Technologie & Digitalisierung ──
    ("15. Technologie & Digitalisierung", "die Digitalisierung", "digitalization"),
    ("15. Technologie & Digitalisierung", "die Digitalisierung der Gesellschaft", "digitalization of society"),
    ("15. Technologie & Digitalisierung", "die Technologie", "technology"),
    ("15. Technologie & Digitalisierung", "die Innovation", "innovation"),
    ("15. Technologie & Digitalisierung", "die technologische Entwicklung", "technological development"),
    ("15. Technologie & Digitalisierung", "der Fortschritt", "progress"),
    ("15. Technologie & Digitalisierung", "die Disruption", "disruption"),
    ("15. Technologie & Digitalisierung", "das Internet", "internet"),
    ("15. Technologie & Digitalisierung", "die Cybersicherheit", "cybersecurity"),
    ("15. Technologie & Digitalisierung", "der Datenschutz", "data protection / privacy"),
    ("15. Technologie & Digitalisierung", "die Datensicherheit", "data security"),
    ("15. Technologie & Digitalisierung", "die DSGVO", "GDPR (EU data protection regulation)"),
    ("15. Technologie & Digitalisierung", "die Big Data", "big data"),
    ("15. Technologie & Digitalisierung", "die Cloud", "cloud (computing)"),
    ("15. Technologie & Digitalisierung", "die Plattform", "platform"),
    ("15. Technologie & Digitalisierung", "der Algorithmus", "algorithm"),
    ("15. Technologie & Digitalisierung", "die Software", "software"),
    ("15. Technologie & Digitalisierung", "die Hardware", "hardware"),
    ("15. Technologie & Digitalisierung", "die App", "app"),
    ("15. Technologie & Digitalisierung", "die digitale Infrastruktur", "digital infrastructure"),
    ("15. Technologie & Digitalisierung", "die digitale Kompetenz", "digital literacy"),
    ("15. Technologie & Digitalisierung", "die digitale Kluft", "digital divide"),
    ("15. Technologie & Digitalisierung", "die Vernetzung", "networking / connectivity"),
    ("15. Technologie & Digitalisierung", "die Automatisierung", "automation"),
    ("15. Technologie & Digitalisierung", "die Robotik", "robotics"),
    ("15. Technologie & Digitalisierung", "innovativ", "innovative"),
    ("15. Technologie & Digitalisierung", "digital", "digital"),
    ("15. Technologie & Digitalisierung", "vernetzt", "connected / networked"),
    ("15. Technologie & Digitalisierung", "digitalisieren", "to digitize"),
    ("15. Technologie & Digitalisierung", "automatisieren", "to automate"),
    # ── 16. KI & Ethik ──
    ("16. KI & Ethik", "die künstliche Intelligenz (KI)", "artificial intelligence (AI)"),
    ("16. KI & Ethik", "das maschinelle Lernen", "machine learning"),
    ("16. KI & Ethik", "das neuronale Netz", "neural network"),
    ("16. KI & Ethik", "der Chatbot", "chatbot"),
    ("16. KI & Ethik", "die Sprachmodell", "language model"),
    ("16. KI & Ethik", "die Automatisierung von Entscheidungen", "automation of decisions"),
    ("16. KI & Ethik", "die ethische Implikation", "ethical implication"),
    ("16. KI & Ethik", "die Ethik", "ethics"),
    ("16. KI & Ethik", "die Moral", "morality"),
    ("16. KI & Ethik", "die Verantwortung", "responsibility"),
    ("16. KI & Ethik", "die Rechenschaft", "accountability"),
    ("16. KI & Ethik", "die Transparenz", "transparency"),
    ("16. KI & Ethik", "die Voreingenommenheit", "bias"),
    ("16. KI & Ethik", "die Diskriminierung durch Algorithmen", "algorithmic discrimination"),
    ("16. KI & Ethik", "die Überwachung", "surveillance"),
    ("16. KI & Ethik", "die Privatsphäre", "privacy"),
    ("16. KI & Ethik", "die Datenhoheit", "data sovereignty"),
    ("16. KI & Ethik", "die Regulierung von KI", "AI regulation"),
    ("16. KI & Ethik", "der Einsatz von KI", "use of AI"),
    ("16. KI & Ethik", "die Chancen und Risiken", "opportunities and risks"),
    ("16. KI & Ethik", "die Zukunftstechnologie", "technology of the future"),
    ("16. KI & Ethik", "ethisch vertretbar", "ethically justifiable"),
    ("16. KI & Ethik", "verantwortungsvoll", "responsible"),
    ("16. KI & Ethik", "regulieren", "to regulate"),
    ("16. KI & Ethik", "überwachen", "to monitor / surveil"),
    # ── 17. Medien & Öffentlichkeit ──
    ("17. Medien & Öffentlichkeit", "die Medien", "media"),
    ("17. Medien & Öffentlichkeit", "die Medienlandschaft", "media landscape"),
    ("17. Medien & Öffentlichkeit", "die Presse", "press"),
    ("17. Medien & Öffentlichkeit", "die Zeitung", "newspaper"),
    ("17. Medien & Öffentlichkeit", "die Nachrichten", "news"),
    ("17. Medien & Öffentlichkeit", "die Berichterstattung", "reporting / coverage"),
    ("17. Medien & Öffentlichkeit", "der Journalismus", "journalism"),
    ("17. Medien & Öffentlichkeit", "der Journalist / die Journalistin", "journalist"),
    ("17. Medien & Öffentlichkeit", "die Redaktion", "editorial office"),
    ("17. Medien & Öffentlichkeit", "die Schlagzeile", "headline"),
    ("17. Medien & Öffentlichkeit", "der Artikel", "article"),
    ("17. Medien & Öffentlichkeit", "der Kommentar", "commentary"),
    ("17. Medien & Öffentlichkeit", "die Meinungsmache", "opinion manipulation"),
    ("17. Medien & Öffentlichkeit", "die Desinformation", "disinformation"),
    ("17. Medien & Öffentlichkeit", "die Fehlinformation", "misinformation"),
    ("17. Medien & Öffentlichkeit", "die Fake News", "fake news"),
    ("17. Medien & Öffentlichkeit", "die Medienkompetenz", "media literacy"),
    ("17. Medien & Öffentlichkeit", "die Öffentlichkeitsarbeit", "public relations"),
    ("17. Medien & Öffentlichkeit", "die Reichweite", "reach / coverage"),
    ("17. Medien & Öffentlichkeit", "die Social-Media-Plattform", "social media platform"),
    ("17. Medien & Öffentlichkeit", "der Influencer / die Influencerin", "influencer"),
    ("17. Medien & Öffentlichkeit", "die Zensur", "censorship"),
    ("17. Medien & Öffentlichkeit", "die Meinungsfreiheit", "freedom of opinion"),
    ("17. Medien & Öffentlichkeit", "berichten", "to report"),
    ("17. Medien & Öffentlichkeit", "verbreiten", "to spread / disseminate"),
    ("17. Medien & Öffentlichkeit", "zensieren", "to censor"),
    ("17. Medien & Öffentlichkeit", "manipulieren", "to manipulate"),
    # ── 18. Umwelt & Klima ──
    ("18. Umwelt & Klima", "die Umwelt", "environment"),
    ("18. Umwelt & Klima", "der Umweltschutz", "environmental protection"),
    ("18. Umwelt & Klima", "der Klimawandel", "climate change"),
    ("18. Umwelt & Klima", "die Erderwärmung", "global warming"),
    ("18. Umwelt & Klima", "der Treibhauseffekt", "greenhouse effect"),
    ("18. Umwelt & Klima", "das Treibhausgas", "greenhouse gas"),
    ("18. Umwelt & Klima", "der CO2-Ausstoß", "CO2 emissions"),
    ("18. Umwelt & Klima", "die Kohlendioxidemission", "carbon dioxide emission"),
    ("18. Umwelt & Klima", "die Klimakrise", "climate crisis"),
    ("18. Umwelt & Klima", "die Klimakonferenz", "climate conference"),
    ("18. Umwelt & Klima", "das Klimaabkommen", "climate agreement"),
    ("18. Umwelt & Klima", "die Klimaneutralität", "climate neutrality"),
    ("18. Umwelt & Klima", "die Klimaziele", "climate targets"),
    ("18. Umwelt & Klima", "der Meeresspiegel", "sea level"),
    ("18. Umwelt & Klima", "die Dürre", "drought"),
    ("18. Umwelt & Klima", "die Überschwemmung", "flood"),
    ("18. Umwelt & Klima", "der Extremwetterereignis", "extreme weather event"),
    ("18. Umwelt & Klima", "die Artenvielfalt", "biodiversity"),
    ("18. Umwelt & Klima", "das Artensterben", "species extinction"),
    ("18. Umwelt & Klima", "die Entwaldung", "deforestation"),
    ("18. Umwelt & Klima", "die Verschmutzung", "pollution"),
    ("18. Umwelt & Klima", "die Luftqualität", "air quality"),
    ("18. Umwelt & Klima", "der ökologische Fußabdruck", "ecological footprint"),
    ("18. Umwelt & Klima", "nachhaltig", "sustainable"),
    ("18. Umwelt & Klima", "klimafreundlich", "climate-friendly"),
    ("18. Umwelt & Klima", "emissionsarm", "low-emission"),
    ("18. Umwelt & Klima", "reduzieren", "to reduce"),
    ("18. Umwelt & Klima", "vermeiden", "to avoid"),
    ("18. Umwelt & Klima", "schützen", "to protect"),
    # ── 19. Energie & Nachhaltigkeit ──
    ("19. Energie & Nachhaltigkeit", "die Energie", "energy"),
    ("19. Energie & Nachhaltigkeit", "die Energiewende", "energy transition"),
    ("19. Energie & Nachhaltigkeit", "die erneuerbare Energie", "renewable energy"),
    ("19. Energie & Nachhaltigkeit", "die Solarenergie", "solar energy"),
    ("19. Energie & Nachhaltigkeit", "die Windenergie", "wind energy"),
    ("19. Energie & Nachhaltigkeit", "die Kernenergie", "nuclear energy"),
    ("19. Energie & Nachhaltigkeit", "die Atomkraft", "nuclear power"),
    ("19. Energie & Nachhaltigkeit", "das Atomkraftwerk", "nuclear power plant"),
    ("19. Energie & Nachhaltigkeit", "die Kohle", "coal"),
    ("19. Energie & Nachhaltigkeit", "das Erdgas", "natural gas"),
    ("19. Energie & Nachhaltigkeit", "das Öl", "oil"),
    ("19. Energie & Nachhaltigkeit", "der Energieverbrauch", "energy consumption"),
    ("19. Energie & Nachhaltigkeit", "die Energieeffizienz", "energy efficiency"),
    ("19. Energie & Nachhaltigkeit", "die Nachhaltigkeit", "sustainability"),
    ("19. Energie & Nachhaltigkeit", "die Ressourcenschonung", "resource conservation"),
    ("19. Energie & Nachhaltigkeit", "die Kreislaufwirtschaft", "circular economy"),
    ("19. Energie & Nachhaltigkeit", "das Recycling", "recycling"),
    ("19. Energie & Nachhaltigkeit", "der Müll", "waste / rubbish"),
    ("19. Energie & Nachhaltigkeit", "die Abfallvermeidung", "waste avoidance"),
    ("19. Energie & Nachhaltigkeit", "die Mülltrennung", "waste separation"),
    ("19. Energie & Nachhaltigkeit", "der Plastikmüll", "plastic waste"),
    ("19. Energie & Nachhaltigkeit", "die Solarpanel", "solar panel"),
    ("19. Energie & Nachhaltigkeit", "die Windkraftanlage", "wind turbine"),
    ("19. Energie & Nachhaltigkeit", "nachhaltig wirtschaften", "to operate sustainably"),
    ("19. Energie & Nachhaltigkeit", "recyceln", "to recycle"),
    # ── 20. Gesundheit & Medizin ──
    ("20. Gesundheit & Medizin", "die Gesundheit", "health"),
    ("20. Gesundheit & Medizin", "die öffentliche Gesundheit", "public health"),
    ("20. Gesundheit & Medizin", "das Gesundheitssystem", "healthcare system"),
    ("20. Gesundheit & Medizin", "die Krankenversicherung", "health insurance"),
    ("20. Gesundheit & Medizin", "die Krankheit", "illness / disease"),
    ("20. Gesundheit & Medizin", "die Pandemie", "pandemic"),
    ("20. Gesundheit & Medizin", "die Epidemie", "epidemic"),
    ("20. Gesundheit & Medizin", "die Impfung", "vaccination"),
    ("20. Gesundheit & Medizin", "der Impfstoff", "vaccine"),
    ("20. Gesundheit & Medizin", "die Prävention", "prevention"),
    ("20. Gesundheit & Medizin", "die Vorsorge", "preventive care"),
    ("20. Gesundheit & Medizin", "die Diagnose", "diagnosis"),
    ("20. Gesundheit & Medizin", "die Therapie", "therapy"),
    ("20. Gesundheit & Medizin", "die Behandlung", "treatment"),
    ("20. Gesundheit & Medizin", "die Medizin", "medicine"),
    ("20. Gesundheit & Medizin", "der Arzt / die Ärztin", "doctor"),
    ("20. Gesundheit & Medizin", "das Krankenhaus", "hospital"),
    ("20. Gesundheit & Medizin", "die Patientenversorgung", "patient care"),
    ("20. Gesundheit & Medizin", "die Lebenserwartung", "life expectancy"),
    ("20. Gesundheit & Medizin", "die Ernährung", "nutrition / diet"),
    ("20. Gesundheit & Medizin", "die Übergewicht", "overweight / obesity"),
    ("20. Gesundheit & Medizin", "die Adipositas", "obesity (medical)"),
    ("20. Gesundheit & Medizin", "präventiv", "preventive"),
    ("20. Gesundheit & Medizin", "behandeln", "to treat"),
    ("20. Gesundheit & Medizin", "heilen", "to heal / cure"),
    ("20. Gesundheit & Medizin", "impfen", "to vaccinate"),
    # ── 21. Psychologie & Verhalten ──
    ("21. Psychologie & Verhalten", "die Psychologie", "psychology"),
    ("21. Psychologie & Verhalten", "die psychische Gesundheit", "mental health"),
    ("21. Psychologie & Verhalten", "die Depression", "depression"),
    ("21. Psychologie & Verhalten", "die Angststörung", "anxiety disorder"),
    ("21. Psychologie & Verhalten", "der Stress", "stress"),
    ("21. Psychologie & Verhalten", "die Belastung", "burden / strain"),
    ("21. Psychologie & Verhalten", "die Resilienz", "resilience"),
    ("21. Psychologie & Verhalten", "die Motivation", "motivation"),
    ("21. Psychologie & Verhalten", "die Wahrnehmung", "perception"),
    ("21. Psychologie & Verhalten", "das Verhalten", "behaviour"),
    ("21. Psychologie & Verhalten", "die Einstellung", "attitude"),
    ("21. Psychologie & Verhalten", "die Vorurteil", "prejudice"),
    ("21. Psychologie & Verhalten", "das Stereotyp", "stereotype"),
    ("21. Psychologie & Verhalten", "die Identität", "identity"),
    ("21. Psychologie & Verhalten", "das Selbstbewusstsein", "self-confidence"),
    ("21. Psychologie & Verhalten", "das Selbstwertgefühl", "self-esteem"),
    ("21. Psychologie & Verhalten", "die Gewohnheit", "habit"),
    ("21. Psychologie & Verhalten", "die Abhängigkeit", "dependency / addiction"),
    ("21. Psychologie & Verhalten", "die Sucht", "addiction"),
    ("21. Psychologie & Verhalten", "die Therapie", "therapy"),
    ("21. Psychologie & Verhalten", "der Psychologe / die Psychologin", "psychologist"),
    ("21. Psychologie & Verhalten", "beeinflussen", "to influence"),
    ("21. Psychologie & Verhalten", "wahrnehmen", "to perceive"),
    ("21. Psychologie & Verhalten", "verhalten", "to behave"),
    # ── 22. Kultur & Identität ──
    ("22. Kultur & Identität", "die Kultur", "culture"),
    ("22. Kultur & Identität", "das Kulturerbe", "cultural heritage"),
    ("22. Kultur & Identität", "die kulturelle Identität", "cultural identity"),
    ("22. Kultur & Identität", "die Vielfalt", "diversity"),
    ("22. Kultur & Identität", "die kulturelle Vielfalt", "cultural diversity"),
    ("22. Kultur & Identität", "die Integration", "integration"),
    ("22. Kultur & Identität", "die Assimilation", "assimilation"),
    ("22. Kultur & Identität", "die interkulturelle Kommunikation", "intercultural communication"),
    ("22. Kultur & Identität", "die Kunst", "art"),
    ("22. Kultur & Identität", "die Literatur", "literature"),
    ("22. Kultur & Identität", "die Musik", "music"),
    ("22. Kultur & Identität", "das Theater", "theatre"),
    ("22. Kultur & Identität", "der Film", "film"),
    ("22. Kultur & Identität", "die Ausstellung", "exhibition"),
    ("22. Kultur & Identität", "das Museum", "museum"),
    ("22. Kultur & Identität", "die Subkultur", "subculture"),
    ("22. Kultur & Identität", "die Popkultur", "pop culture"),
    ("22. Kultur & Identität", "die Tradition", "tradition"),
    ("22. Kultur & Identität", "der Brauch", "custom"),
    ("22. Kultur & Identität", "die Werte", "values"),
    ("22. Kultur & Identität", "die Norm", "norm"),
    ("22. Kultur & Identität", "kulturell", "cultural"),
    ("22. Kultur & Identität", "vielfältig", "diverse"),
    # ── 23. Migration & Integration ──
    ("23. Migration & Integration", "die Migration", "migration"),
    ("23. Migration & Integration", "der Migrant / die Migrantin", "migrant"),
    ("23. Migration & Integration", "der Zuwanderer / die Zuwanderin", "immigrant"),
    ("23. Migration & Integration", "die Zuwanderung", "immigration"),
    ("23. Migration & Integration", "die Einwanderung", "immigration"),
    ("23. Migration & Integration", "die Auswanderung", "emigration"),
    ("23. Migration & Integration", "die Flucht", "flight / escape"),
    ("23. Migration & Integration", "der Flüchtling / die Flüchtlingin", "refugee"),
    ("23. Migration & Integration", "das Asyl", "asylum"),
    ("23. Migration & Integration", "der Asylantrag", "asylum application"),
    ("23. Migration & Integration", "die Abschiebung", "deportation"),
    ("23. Migration & Integration", "die Integration", "integration"),
    ("23. Migration & Integration", "die Integrationspolitik", "integration policy"),
    ("23. Migration & Integration", "die Sprachkurs", "language course"),
    ("23. Migration & Integration", "die Einbürgerung", "naturalization"),
    ("23. Migration & Integration", "die Staatsangehörigkeit", "nationality / citizenship"),
    ("23. Migration & Integration", "die Herkunft", "origin"),
    ("23. Migration & Integration", "die kulturelle Anerkennung", "cultural recognition"),
    ("23. Migration & Integration", "die Ausgrenzung", "exclusion / marginalization"),
    ("23. Migration & Integration", "die Diskriminierung", "discrimination"),
    ("23. Migration & Integration", "integrieren", "to integrate"),
    ("23. Migration & Integration", "ausgrenzen", "to exclude / marginalize"),
    ("23. Migration & Integration", "abschieben", "to deport"),
    # ── 24. Globalisierung & Entwicklung ──
    ("24. Globalisierung", "die Globalisierung", "globalization"),
    ("24. Globalisierung", "die Weltwirtschaft", "world economy"),
    ("24. Globalisierung", "die Entwicklungsländer", "developing countries"),
    ("24. Globalisierung", "die Industrieländer", "industrialized countries"),
    ("24. Globalisierung", "die Schwellenländer", "emerging economies"),
    ("24. Globalisierung", "die Entwicklungshilfe", "development aid"),
    ("24. Globalisierung", "die Armut", "poverty"),
    ("24. Globalisierung", "die Armutsbekämpfung", "poverty reduction"),
    ("24. Globalisierung", "die soziale Ungleichheit", "social inequality"),
    ("24. Globalisierung", "die Kluft zwischen Arm und Reich", "gap between rich and poor"),
    ("24. Globalisierung", "die Wohlstand", "prosperity / wealth"),
    ("24. Globalisierung", "der Lebensstandard", "standard of living"),
    ("24. Globalisierung", "die Entwicklung", "development"),
    ("24. Globalisierung", "die Nachhaltige Entwicklung", "sustainable development"),
    ("24. Globalisierung", "die Millenniumsziele", "millennium goals"),
    ("24. Globalisierung", "die internationale Zusammenarbeit", "international cooperation"),
    ("24. Globalisierung", "die Welthandelsorganisation (WTO)", "World Trade Organization"),
    ("24. Globalisierung", "die Europäische Union (EU)", "European Union"),
    ("24. Globalisierung", "global", "global"),
    ("24. Globalisierung", "international", "international"),
    ("24. Globalisierung", "entwickeln", "to develop"),
    # ── 25. Konflikt & Sicherheit ──
    ("25. Konflikt & Sicherheit", "der Konflikt", "conflict"),
    ("25. Konflikt & Sicherheit", "der Krieg", "war"),
    ("25. Konflikt & Sicherheit", "der Frieden", "peace"),
    ("25. Konflikt & Sicherheit", "die Friedenssicherung", "peacekeeping"),
    ("25. Konflikt & Sicherheit", "die Waffenruhe", "ceasefire"),
    ("25. Konflikt & Sicherheit", "die Diplomatie", "diplomacy"),
    ("25. Konflikt & Sicherheit", "die Verhandlung", "negotiation"),
    ("25. Konflikt & Sicherheit", "die Sicherheit", "security"),
    ("25. Konflikt & Sicherheit", "die innere Sicherheit", "internal security"),
    ("25. Konflikt & Sicherheit", "die äußere Sicherheit", "external security"),
    ("25. Konflikt & Sicherheit", "der Terrorismus", "terrorism"),
    ("25. Konflikt & Sicherheit", "der Anschlag", "attack / assault"),
    ("25. Konflikt & Sicherheit", "die Bedrohung", "threat"),
    ("25. Konflikt & Sicherheit", "die Verteidigung", "defence"),
    ("25. Konflikt & Sicherheit", "die Rüstung", "armament"),
    ("25. Konflikt & Sicherheit", "die Abrüstung", "disarmament"),
    ("25. Konflikt & Sicherheit", "die Sanktion", "sanction"),
    ("25. Konflikt & Sicherheit", "die Drohung", "threat"),
    ("25. Konflikt & Sicherheit", "verhandeln", "to negotiate"),
    ("25. Konflikt & Sicherheit", "eskalieren", "to escalate"),
    ("25. Konflikt & Sicherheit", "deeskalieren", "to de-escalate"),
    # ── 26. Sprechen — Präsentation & Diskussion ──
    ("26. Sprechen (C1)", "Ich möchte Ihnen heute … vorstellen", "Today I would like to present … to you"),
    ("26. Sprechen (C1)", "Das Thema meiner Präsentation ist", "The topic of my presentation is"),
    ("26. Sprechen (C1)", "Zunächst werde ich auf … eingehen", "First I will address …"),
    ("26. Sprechen (C1)", "Anschließend möchte ich erläutern, warum", "Subsequently I would like to explain why"),
    ("26. Sprechen (C1)", "Abschließend werde ich zusammenfassen", "Finally I will summarize"),
    ("26. Sprechen (C1)", "Ich komme nun zu meinem nächsten Punkt", "I now come to my next point"),
    ("26. Sprechen (C1)", "Lassen Sie mich ein Beispiel anführen", "Let me give an example"),
    ("26. Sprechen (C1)", "Wie ich bereits erwähnt habe", "As I have already mentioned"),
    ("26. Sprechen (C1)", "Daraus schließe ich, dass", "From this I conclude that"),
    ("26. Sprechen (C1)", "Haben Sie dazu eine Frage?", "Do you have a question about this?"),
    ("26. Sprechen (C1)", "Das ist ein interessanter Einwand", "That is an interesting objection"),
    ("26. Sprechen (C1)", "Da stimme ich Ihnen zu, allerdings …", "I agree with you there, however …"),
    ("26. Sprechen (C1)", "Da muss ich Ihnen widersprechen, weil", "I must disagree with you, because"),
    ("26. Sprechen (C1)", "Könnten Sie das näher erläutern?", "Could you elaborate on that?"),
    ("26. Sprechen (C1)", "Ich sehe das etwas anders", "I see that somewhat differently"),
    ("26. Sprechen (C1)", "Meiner Erfahrung nach", "In my experience"),
    ("26. Sprechen (C1)", "die Präsentation halten", "to give a presentation"),
    ("26. Sprechen (C1)", "die Diskussion führen", "to lead a discussion"),
    ("26. Sprechen (C1)", "argumentieren", "to argue"),
    ("26. Sprechen (C1)", "erläutern", "to explain / elaborate"),
    # ── 27. Konjunktiv & Modalität (C1) ──
    ("27. Konjunktiv & Modalität", "Man könnte argumentieren, dass", "One could argue that"),
    ("27. Konjunktiv & Modalität", "Es sollte berücksichtigt werden, dass", "It should be taken into account that"),
    ("27. Konjunktiv & Modalität", "Es wäre wünschenswert, wenn", "It would be desirable if"),
    ("27. Konjunktiv & Modalität", "Es wäre denkbar, dass", "It would be conceivable that"),
    ("27. Konjunktiv & Modalität", "Es ließe sich feststellen, dass", "It could be established that"),
    ("27. Konjunktiv & Modalität", "Es sei darauf hingewiesen, dass", "It should be pointed out that (formal)"),
    ("27. Konjunktiv & Modalität", "Angenommen, es gäbe …", "Suppose there were …"),
    ("27. Konjunktiv & Modalität", "Falls dies der Fall wäre", "If this were the case"),
    ("27. Konjunktiv & Modalität", "Hätte man …, wäre …", "Had one …, … would be"),
    ("27. Konjunktiv & Modalität", "Es ist anzunehmen, dass", "It is to be assumed that"),
    ("27. Konjunktiv & Modalität", "Es ist davon auszugehen, dass", "It is to be expected that"),
    ("27. Konjunktiv & Modalität", "Es ist unwahrscheinlich, dass", "It is unlikely that"),
    ("27. Konjunktiv & Modalität", "Es ist wahrscheinlich, dass", "It is likely that"),
    ("27. Konjunktiv & Modalität", "Es ist unvermeidlich, dass", "It is inevitable that"),
    ("27. Konjunktiv & Modalität", "Es ist unerlässlich, dass", "It is essential that"),
    ("27. Konjunktiv & Modalität", "Es ist ratsam, … zu", "It is advisable to …"),
    ("27. Konjunktiv & Modalität", "Es empfiehlt sich, … zu", "It is recommended to …"),
    ("27. Konjunktiv & Modalität", "möglicherweise", "possibly"),
    ("27. Konjunktiv & Modalität", "vermutlich", "presumably"),
    ("27. Konjunktiv & Modalität", "angeblich", "allegedly"),
    ("27. Konjunktiv & Modalität", "mutmaßlich", "presumably / allegedly"),
    ("27. Konjunktiv & Modalität", "hypothetisch", "hypothetical"),
    # ── 28. C1-Verben (hoch frequent) ──
    ("28. C1-Verben", "analysieren", "to analyse"),
    ("28. C1-Verben", "beurteilen", "to assess / judge"),
    ("28. C1-Verben", "bewerten", "to evaluate"),
    ("28. C1-Verben", "einschätzen", "to estimate / assess"),
    ("28. C1-Verben", "erörtern", "to discuss / examine"),
    ("28. C1-Verben", "erläutern", "to explain / elaborate"),
    ("28. C1-Verben", "darlegen", "to set out / present"),
    ("28. C1-Verben", "begründen", "to justify"),
    ("28. C1-Verben", "widerlegen", "to refute"),
    ("28. C1-Verben", "bestätigen", "to confirm"),
    ("28. C1-Verben", "verneinen", "to deny"),
    ("28. C1-Verben", "zustimmen", "to agree"),
    ("28. C1-Verben", "widersprechen", "to contradict / disagree"),
    ("28. C1-Verben", "kritisieren", "to criticize"),
    ("28. C1-Verben", "empfehlen", "to recommend"),
    ("28. C1-Verben", "fordern", "to demand / call for"),
    ("28. C1-Verben", "verlangen", "to require / demand"),
    ("28. C1-Verben", "vorschlagen", "to propose"),
    ("28. C1-Verben", "implementieren", "to implement"),
    ("28. C1-Verben", "umsetzen", "to implement / put into practice"),
    ("28. C1-Verben", "optimieren", "to optimize"),
    ("28. C1-Verben", "verbessern", "to improve"),
    ("28. C1-Verben", "verschlechtern", "to worsen"),
    ("28. C1-Verben", "verringern", "to reduce"),
    ("28. C1-Verben", "erhöhen", "to increase"),
    ("28. C1-Verben", "steigern", "to increase / boost"),
    ("28. C1-Verben", "senken", "to lower / reduce"),
    ("28. C1-Verben", "verhindern", "to prevent"),
    ("28. C1-Verben", "ermöglichen", "to enable / make possible"),
    ("28. C1-Verben", "gewährleisten", "to guarantee / ensure"),
    ("28. C1-Verben", "sicherstellen", "to ensure"),
    ("28. C1-Verben", "beeinträchtigen", "to impair / adversely affect"),
    ("28. C1-Verben", "beeinflussen", "to influence"),
    ("28. C1-Verben", "mitverursachen", "to co-cause / contribute to"),
    ("28. C1-Verben", "zurückführen auf", "to attribute to"),
    ("28. C1-Verben", "resultieren aus", "to result from"),
    ("28. C1-Verben", "resultieren in", "to result in"),
    ("28. C1-Verben", "hervorbringen", "to produce / generate"),
    ("28. C1-Verben", "hervorrufen", "to cause / trigger"),
    ("28. C1-Verben", "auslösen", "to trigger / set off"),
    ("28. C1-Verben", "verursachen", "to cause"),
    ("28. C1-Verben", "berücksichtigen", "to take into account"),
    ("28. C1-Verben", "ignorieren", "to ignore"),
    ("28. C1-Verben", "vernachlässigen", "to neglect"),
    ("28. C1-Verben", "priorisieren", "to prioritize"),
    ("28. C1-Verben", "fördern", "to promote / support"),
    ("28. C1-Verben", "hemmen", "to inhibit / hinder"),
    ("28. C1-Verben", "unterstützen", "to support"),
    ("28. C1-Verben", "behindern", "to hinder / obstruct"),
    ("28. C1-Verben", "ermutigen", "to encourage"),
    ("28. C1-Verben", "entmutigen", "to discourage"),
    # ── 29. C1-Adjektive ──
    ("29. C1-Adjektive", "komplex", "complex"),
    ("29. C1-Adjektive", "vielschichtig", "multifaceted"),
    ("29. C1-Adjektive", "differenziert", "differentiated / nuanced"),
    ("29. C1-Adjektive", "eindeutig", "unambiguous / clear"),
    ("29. C1-Adjektive", "mehrdeutig", "ambiguous"),
    ("29. C1-Adjektive", "widersprüchlich", "contradictory"),
    ("29. C1-Adjektive", "kohärent", "coherent"),
    ("29. C1-Adjektive", "schlüssig", "conclusive / coherent"),
    ("29. C1-Adjektive", "überzeugend", "convincing"),
    ("29. C1-Adjektive", "fundamental", "fundamental"),
    ("29. C1-Adjektive", "wesentlich", "essential"),
    ("29. C1-Adjektive", "marginal", "marginal"),
    ("29. C1-Adjektive", "signifikant", "significant"),
    ("29. C1-Adjektive", "erheblich", "considerable / substantial"),
    ("29. C1-Adjektive", "geringfügig", "minor / negligible"),
    ("29. C1-Adjektive", "unverhältnismäßig", "disproportionate"),
    ("29. C1-Adjektive", "verhältnismäßig", "proportionate"),
    ("29. C1-Adjektive", "nachhaltig", "sustainable / lasting"),
    ("29. C1-Adjektive", "kurzfristig", "short-term"),
    ("29. C1-Adjektive", "langfristig", "long-term"),
    ("29. C1-Adjektive", "mittelfristig", "medium-term"),
    ("29. C1-Adjektive", "aktuell", "current"),
    ("29. C1-Adjektive", "zeitgemäß", "contemporary / up-to-date"),
    ("29. C1-Adjektive", "veraltet", "outdated"),
    ("29. C1-Adjektive", "innovativ", "innovative"),
    ("29. C1-Adjektive", "konventionell", "conventional"),
    ("29. C1-Adjektive", "alternativ", "alternative"),
    ("29. C1-Adjektive", "effizient", "efficient"),
    ("29. C1-Adjektive", "ineffizient", "inefficient"),
    ("29. C1-Adjektive", "wirksam", "effective"),
    ("29. C1-Adjektive", "unwirksam", "ineffective"),
    ("29. C1-Adjektive", "angemessen", "appropriate"),
    ("29. C1-Adjektive", "unangemessen", "inappropriate"),
    ("29. C1-Adjektive", "unverzichtbar", "indispensable"),
    ("29. C1-Adjektive", "entbehrlich", "dispensable"),
    ("29. C1-Adjektive", "unvermeidlich", "inevitable"),
    ("29. C1-Adjektive", "vermeidbar", "avoidable"),
    ("29. C1-Adjektive", "dringend", "urgent"),
    ("29. C1-Adjektive", "prioritär", "priority"),
    # ── 30. C1-Abstrakta & Fachbegriffe ──
    ("30. C1-Abstrakta", "die Herausforderung", "challenge"),
    ("30. C1-Abstrakta", "die Chance", "opportunity"),
    ("30. C1-Abstrakta", "das Risiko", "risk"),
    ("30. C1-Abstrakta", "die Gefahr", "danger"),
    ("30. C1-Abstrakta", "der Vorteil", "advantage"),
    ("30. C1-Abstrakta", "der Nachteil", "disadvantage"),
    ("30. C1-Abstrakta", "der Nutzen", "benefit / utility"),
    ("30. C1-Abstrakta", "der Schaden", "damage / harm"),
    ("30. C1-Abstrakta", "die Wirkung", "effect"),
    ("30. C1-Abstrakta", "die Auswirkung", "impact / effect"),
    ("30. C1-Abstrakta", "die Konsequenz", "consequence"),
    ("30. C1-Abstrakta", "die Ursache", "cause"),
    ("30. C1-Abstrakta", "die Folge", "consequence / result"),
    ("30. C1-Abstrakta", "der Zusammenhang", "context / connection"),
    ("30. C1-Abstrakta", "der Sachverhalt", "facts / state of affairs"),
    ("30. C1-Abstrakta", "die Problematik", "problem / issue"),
    ("30. C1-Abstrakta", "die Lösung", "solution"),
    ("30. C1-Abstrakta", "die Maßnahme", "measure / step"),
    ("30. C1-Abstrakta", "die Strategie", "strategy"),
    ("30. C1-Abstrakta", "das Konzept", "concept"),
    ("30. C1-Abstrakta", "der Ansatz", "approach"),
    ("30. C1-Abstrakta", "die Perspektive", "perspective"),
    ("30. C1-Abstrakta", "der Standpunkt", "standpoint / position"),
    ("30. C1-Abstrakta", "die Position", "position"),
    ("30. C1-Abstrakta", "die Stellungnahme", "statement of position"),
    ("30. C1-Abstrakta", "die Erörterung", "discursive essay / examination"),
    ("30. C1-Abstrakta", "die Argumentation", "argumentation"),
    ("30. C1-Abstrakta", "die Begründung", "justification"),
    ("30. C1-Abstrakta", "die Diskussion", "discussion"),
    ("30. C1-Abstrakta", "die Debatte", "debate"),
    ("30. C1-Abstrakta", "die Kontroverse", "controversy"),
    ("30. C1-Abstrakta", "der Konsens", "consensus"),
    ("30. C1-Abstrakta", "der Kompromiss", "compromise"),
    ("30. C1-Abstrakta", "die Einigung", "agreement"),
    ("30. C1-Abstrakta", "die Einigkeit", "unity / agreement"),
    ("30. C1-Abstrakta", "die Spaltung", "division / split"),
    ("30. C1-Abstrakta", "die Polarisierung", "polarization"),
    ("30. C1-Abstrakta", "die Tendenz", "tendency / trend"),
    ("30. C1-Abstrakta", "der Trend", "trend"),
    ("30. C1-Abstrakta", "die Entwicklung", "development"),
    ("30. C1-Abstrakta", "die Veränderung", "change"),
    ("30. C1-Abstrakta", "die Transformation", "transformation"),
    ("30. C1-Abstrakta", "die Modernisierung", "modernization"),
    # ── 31. Schreiben — Forum (Teil 1) ──
    ("31. Schreiben — Forum", "Ich möchte mich an dieser Diskussion beteiligen, weil", "I would like to join this discussion because"),
    ("31. Schreiben — Forum", "Aus meiner Sicht ist es wichtig, dass", "From my point of view it is important that"),
    ("31. Schreiben — Forum", "Ich schließe mich der Meinung an, dass", "I agree with the view that"),
    ("31. Schreiben — Forum", "Ich kann dem Beitrag nur teilweise zustimmen", "I can only partly agree with this post"),
    ("31. Schreiben — Forum", "Mit Verlaub, aber ich sehe das anders", "With respect, I see it differently"),
    ("31. Schreiben — Forum", "Es verwundert mich, dass … so selten thematisiert wird", "It surprises me that … is so rarely discussed"),
    ("31. Schreiben — Forum", "Was oft übersehen wird, ist", "What is often overlooked is"),
    ("31. Schreiben — Forum", "Ein Punkt, der in der Debatte zu kurz kommt, ist", "A point that gets too little attention in the debate is"),
    ("31. Schreiben — Forum", "Ich möchte ergänzen, dass", "I would like to add that"),
    ("31. Schreiben — Forum", "Lassen Sie mich ein persönliches Beispiel anführen", "Let me give a personal example"),
    ("31. Schreiben — Forum", "In meinem Umfeld beobachte ich, dass", "In my environment I observe that"),
    ("31. Schreiben — Forum", "Die öffentliche Diskussion sollte stärker berücksichtigen, dass", "Public debate should take more account of the fact that"),
    ("31. Schreiben — Forum", "der Diskussionsbeitrag", "discussion post / forum contribution"),
    ("31. Schreiben — Forum", "das Online-Forum", "online forum"),
    ("31. Schreiben — Forum", "die Leserin / der Leser", "reader (f/m)"),
    ("31. Schreiben — Forum", "die Kommentarspalte", "comments section"),
    ("31. Schreiben — Forum", "neutraler Ton", "neutral tone"),
    ("31. Schreiben — Forum", "sachlich argumentieren", "to argue objectively"),
    ("31. Schreiben — Forum", "zur Sprache bringen", "to raise (a topic)"),
    ("31. Schreiben — Forum", "Stellung beziehen", "to take a position"),
    # ── 32. Schreiben — Formelle E-Mail (Teil 2) ──
    ("32. Schreiben — E-Mail", "Sehr geehrte Frau …,", "Dear Ms … (formal)"),
    ("32. Schreiben — E-Mail", "Sehr geehrter Herr …,", "Dear Mr … (formal)"),
    ("32. Schreiben — E-Mail", "Sehr geehrte Damen und Herren,", "Dear Sir or Madam,"),
    ("32. Schreiben — E-Mail", "bezugnehmend auf unser Telefonat vom …", "with reference to our phone call on …"),
    ("32. Schreiben — E-Mail", "bezugnehmend auf Ihre E-Mail vom …", "with reference to your email of …"),
    ("32. Schreiben — E-Mail", "hiermit möchte ich mich bei Ihnen beschweren", "herewith I would like to lodge a complaint with you"),
    ("32. Schreiben — E-Mail", "Ich wende mich an Sie, weil", "I am contacting you because"),
    ("32. Schreiben — E-Mail", "Leider muss ich Ihnen mitteilen, dass", "Unfortunately I must inform you that"),
    ("32. Schreiben — E-Mail", "Es ist mir wichtig, darauf hinzuweisen, dass", "It is important to me to point out that"),
    ("32. Schreiben — E-Mail", "Ich bitte Sie höflich, … zu überprüfen", "I kindly ask you to check …"),
    ("32. Schreiben — E-Mail", "Ich wäre Ihnen dankbar, wenn Sie … könnten", "I would be grateful if you could …"),
    ("32. Schreiben — E-Mail", "Könnten Sie mir bitte mitteilen, ob …", "Could you please let me know whether …"),
    ("32. Schreiben — E-Mail", "Ich erwarte, dass das Problem umgehend behoben wird", "I expect the problem to be resolved promptly"),
    ("32. Schreiben — E-Mail", "Für Ihre Bemühungen bedanke ich mich im Voraus", "Thank you in advance for your efforts"),
    ("32. Schreiben — E-Mail", "Mit freundlichen Grüßen", "Yours sincerely / Kind regards"),
    ("32. Schreiben — E-Mail", "die Beschwerde", "complaint"),
    ("32. Schreiben — E-Mail", "der Missstand", "malpractice / unacceptable situation"),
    ("32. Schreiben — E-Mail", "die Unannehmlichkeit", "inconvenience"),
    ("32. Schreiben — E-Mail", "die Bitte", "request"),
    ("32. Schreiben — E-Mail", "die Klärung", "clarification"),
    ("32. Schreiben — E-Mail", "die Rückmeldung", "feedback / response"),
    ("32. Schreiben — E-Mail", "die Frist", "deadline"),
    ("32. Schreiben — E-Mail", "die Verzögerung", "delay"),
    ("32. Schreiben — E-Mail", "die Zusage", "commitment / promise"),
    ("32. Schreiben — E-Mail", "die Absage", "rejection / cancellation"),
    ("32. Schreiben — E-Mail", "die Entschuldigung", "apology"),
    ("32. Schreiben — E-Mail", "sich beschweren", "to complain"),
    ("32. Schreiben — E-Mail", "nachfragen", "to follow up / inquire"),
    ("32. Schreiben — E-Mail", "kündigen", "to give notice / terminate"),
    ("32. Schreiben — E-Mail", "bestätigen", "to confirm"),
    ("32. Schreiben — E-Mail", "ablehnen", "to reject / decline"),
    # ── 33. Recht, Verwaltung & Datenschutz ──
    ("33. Recht & Datenschutz", "das Recht", "law / right"),
    ("33. Recht & Datenschutz", "die Gesetzgebung", "legislation"),
    ("33. Recht & Datenschutz", "die Verordnung", "regulation / ordinance"),
    ("33. Recht & Datenschutz", "die Richtlinie", "guideline / directive"),
    ("33. Recht & Datenschutz", "die Klausel", "clause"),
    ("33. Recht & Datenschutz", "die Bestimmung", "provision / regulation"),
    ("33. Recht & Datenschutz", "die Vorschrift", "rule / regulation"),
    ("33. Recht & Datenschutz", "die Regulierung", "regulation"),
    ("33. Recht & Datenschutz", "die Deregulierung", "deregulation"),
    ("33. Recht & Datenschutz", "die Verpflichtung", "obligation"),
    ("33. Recht & Datenschutz", "die Haftung", "liability"),
    ("33. Recht & Datenschutz", "die Zuständigkeit", "responsibility / jurisdiction"),
    ("33. Recht & Datenschutz", "die Instanz", "authority / instance (legal/admin)"),
    ("33. Recht & Datenschutz", "der Ausschuss", "committee"),
    ("33. Recht & Datenschutz", "die Akte", "file / record (admin)"),
    ("33. Recht & Datenschutz", "die Anordnung", "order / directive"),
    ("33. Recht & Datenschutz", "die Persönlichkeitsrechte", "personal/privacy rights"),
    ("33. Recht & Datenschutz", "das Persönlichkeitsrecht", "right to privacy / personality rights"),
    ("33. Recht & Datenschutz", "der Datenschutz", "data protection"),
    ("33. Recht & Datenschutz", "die Datensicherheit", "data security"),
    ("33. Recht & Datenschutz", "die Datenverarbeitung", "data processing"),
    ("33. Recht & Datenschutz", "die Datenerhebung", "data collection"),
    ("33. Recht & Datenschutz", "die Speicherung personenbezogener Daten", "storage of personal data"),
    ("33. Recht & Datenschutz", "die Einwilligung", "consent"),
    ("33. Recht & Datenschutz", "die Datenweitergabe", "transfer of data"),
    ("33. Recht & Datenschutz", "der Missbrauch", "misuse / abuse"),
    ("33. Recht & Datenschutz", "der Datenmissbrauch", "data misuse"),
    ("33. Recht & Datenschutz", "die Identität", "identity"),
    ("33. Recht & Datenschutz", "die Anonymität", "anonymity"),
    ("33. Recht & Datenschutz", "die Transparenz", "transparency"),
    ("33. Recht & Datenschutz", "die Aufklärung", "enlightenment / education (of public)"),
    ("33. Recht & Datenschutz", "gesetzlich verankern", "to enshrine in law"),
    ("33. Recht & Datenschutz", "rechtswidrig", "unlawful"),
    ("33. Recht & Datenschutz", "rechtskräftig", "legally binding"),
    ("33. Recht & Datenschutz", "verbindlich", "binding"),
    ("33. Recht & Datenschutz", "zulässig", "permissible / allowed"),
    ("33. Recht & Datenschutz", "unzulässig", "inadmissible / not permitted"),
    # ── 34. Kollokationen (C1) ──
    ("34. Kollokationen", "eine Entscheidung treffen", "to make a decision"),
    ("34. Kollokationen", "Verantwortung übernehmen", "to take responsibility"),
    ("34. Kollokationen", "Verantwortung tragen", "to bear responsibility"),
    ("34. Kollokationen", "Kritik üben", "to criticize"),
    ("34. Kollokationen", "Kritik ernten", "to receive criticism"),
    ("34. Kollokationen", "Maßnahmen ergreifen", "to take measures"),
    ("34. Kollokationen", "Schritte unternehmen", "to take steps"),
    ("34. Kollokationen", "Bedenken äußern", "to express concerns"),
    ("34. Kollokationen", "Einwände vorbringen", "to raise objections"),
    ("34. Kollokationen", "Einfluss nehmen auf", "to exert influence on"),
    ("34. Kollokationen", "Einfluss ausüben", "to exert influence"),
    ("34. Kollokationen", "zur Debatte stehen", "to be up for debate"),
    ("34. Kollokationen", "zur Sprache kommen", "to come up for discussion"),
    ("34. Kollokationen", "in Frage stellen", "to call into question"),
    ("34. Kollokationen", "in Betracht ziehen", "to take into consideration"),
    ("34. Kollokationen", "zur Verfügung stellen", "to make available"),
    ("34. Kollokationen", "zur Verfügung stehen", "to be available"),
    ("34. Kollokationen", "Anklage finden", "to meet with approval"),
    ("34. Kollokationen", "Beachtung finden", "to receive attention"),
    ("34. Kollokationen", "Kritik erfahren", "to receive criticism"),
    ("34. Kollokationen", "eine Rolle spielen", "to play a role"),
    ("34. Kollokationen", "einen Beitrag leisten", "to make a contribution"),
    ("34. Kollokationen", "einen Unterschied machen", "to make a difference"),
    ("34. Kollokationen", "einen Eindruck hinterlassen", "to leave an impression"),
    ("34. Kollokationen", "einen Vorschlag unterbreiten", "to submit a proposal"),
    ("34. Kollokationen", "eine Lösung finden", "to find a solution"),
    ("34. Kollokationen", "einen Kompromiss eingehen", "to accept a compromise"),
    ("34. Kollokationen", "einen Konsens erzielen", "to reach a consensus"),
    ("34. Kollokationen", "eine Debatte führen", "to conduct a debate"),
    ("34. Kollokationen", "eine Diskussion anstoßen", "to initiate a discussion"),
    ("34. Kollokationen", "eine Stellungnahme abgeben", "to issue a statement"),
    ("34. Kollokationen", "einen Standpunkt vertreten", "to represent a standpoint"),
    ("34. Kollokationen", "eine These aufstellen", "to put forward a thesis"),
    ("34. Kollokationen", "einen Schluss ziehen", "to draw a conclusion"),
    ("34. Kollokationen", "eine Schlussfolgerung ziehen", "to draw a conclusion"),
    ("34. Kollokationen", "sich Sorgen machen um", "to worry about"),
    ("34. Kollokationen", "Rücksicht nehmen auf", "to show consideration for"),
    ("34. Kollokationen", "Rücksicht auf etwas nehmen", "to take something into account"),
    ("34. Kollokationen", "Wert legen auf", "to attach importance to"),
    ("34. Kollokationen", "Nachdruck legen auf", "to emphasize / stress"),
    ("34. Kollokationen", "den Schwerpunkt legen auf", "to focus on"),
    ("34. Kollokationen", "in Kraft treten", "to come into force"),
    ("34. Kollokationen", "in Anspruch nehmen", "to make use of / claim"),
    ("34. Kollokationen", "zur Anwendung kommen", "to be applied"),
    # ── 35. Präsentation (Sprechen Teil 1) ──
    ("35. Präsentation", "Guten Tag, mein Name ist … und ich möchte heute über … sprechen", "Good day, my name is … and today I would like to talk about …"),
    ("35. Präsentation", "Das Thema meines Vortrags lautet", "The topic of my presentation is"),
    ("35. Präsentation", "Ich habe mich für dieses Thema entschieden, weil", "I chose this topic because"),
    ("35. Präsentation", "Zunächst gebe ich einen Überblick über", "First I will give an overview of"),
    ("35. Präsentation", "Im ersten Teil meines Vortrags erläutere ich", "In the first part of my talk I will explain"),
    ("35. Präsentation", "Im Anschluss werde ich auf … eingehen", "Next I will address …"),
    ("35. Präsentation", "Anschließend möchte ich erörtern, inwieweit", "Subsequently I would like to examine to what extent"),
    ("35. Präsentation", "Ein weiterer wichtiger Aspekt ist", "Another important aspect is"),
    ("35. Präsentation", "Nun komme ich zu meinem zweiten Punkt", "Now I come to my second point"),
    ("35. Präsentation", "Lassen Sie mich an dieser Stelle ein Beispiel nennen", "Let me mention an example at this point"),
    ("35. Präsentation", "Wie bereits erwähnt", "As already mentioned"),
    ("35. Präsentation", "Zusammenfassend lässt sich sagen", "In summary, one can say"),
    ("35. Präsentation", "Abschließend möchte ich betonen, dass", "In conclusion I would like to emphasize that"),
    ("35. Präsentation", "Ich danke Ihnen für Ihre Aufmerksamkeit", "Thank you for your attention"),
    ("35. Präsentation", "Ich stehe Ihnen nun für Fragen zur Verfügung", "I am now available for your questions"),
    ("35. Präsentation", "Gibt es dazu Fragen?", "Are there any questions about this?"),
    ("35. Präsentation", "Das ist eine berechtigte Frage", "That is a legitimate question"),
    ("35. Präsentation", "Darauf kann ich folgendermaßen antworten", "I can answer that as follows"),
    ("35. Präsentation", "Das habe ich in meinem Vortrag bereits angesprochen", "I already addressed that in my presentation"),
    ("35. Präsentation", "Das würde den Rahmen sprengen, deshalb kurz", "That would exceed the scope, so briefly …"),
    ("35. Präsentation", "der Vortrag", "lecture / presentation"),
    ("35. Präsentation", "die Präsentation", "presentation"),
    ("35. Präsentation", "die Gliederung", "structure / outline"),
    ("35. Präsentation", "der Überblick", "overview"),
    ("35. Präsentation", "das Publikum", "audience"),
    ("35. Präsentation", "die Zuhörerschaft", "audience (listeners)"),
    ("35. Präsentation", "vortragen", "to present / deliver (a talk)"),
    ("35. Präsentation", "erläutern", "to explain / elaborate"),
    ("35. Präsentation", "strukturieren", "to structure"),
    ("35. Präsentation", "gliedern", "to structure / divide into sections"),
    # ── 36. Psychologie & Verhalten (erweitert) ──
    ("36. Psychologie (erweitert)", "die Wahrnehmung", "perception"),
    ("36. Psychologie (erweitert)", "die Kognition", "cognition"),
    ("36. Psychologie (erweitert)", "die Emotion", "emotion"),
    ("36. Psychologie (erweitert)", "die Emotionsregulation", "emotion regulation"),
    ("36. Psychologie (erweitert)", "die Gewohnheitsbildung", "habit formation"),
    ("36. Psychologie (erweitert)", "die Verhaltensänderung", "behaviour change"),
    ("36. Psychologie (erweitert)", "die kognitive Dissonanz", "cognitive dissonance"),
    ("36. Psychologie (erweitert)", "die Bestätigungstendenz", "confirmation bias"),
    ("36. Psychologie (erweitert)", "der Gruppenzwang", "peer pressure / group pressure"),
    ("36. Psychologie (erweitert)", "die Konformität", "conformity"),
    ("36. Psychologie (erweitert)", "die Empathie", "empathy"),
    ("36. Psychologie (erweitert)", "die Anteilnahme", "sympathy / compassion"),
    ("36. Psychologie (erweitert)", "die Selbstwirksamkeit", "self-efficacy"),
    ("36. Psychologie (erweitert)", "die Selbstkontrolle", "self-control"),
    ("36. Psychologie (erweitert)", "die Impulskontrolle", "impulse control"),
    ("36. Psychologie (erweitert)", "die Belastbarkeit", "resilience / stress tolerance"),
    ("36. Psychologie (erweitert)", "die Überforderung", "overwhelm / overload"),
    ("36. Psychologie (erweitert)", "die Auswirkung auf die Psyche", "impact on mental health"),
    ("36. Psychologie (erweitert)", "psychisch belastet", "mentally strained"),
    ("36. Psychologie (erweitert)", "psychisch stabil", "mentally stable"),
    ("36. Psychologie (erweitert)", "nachvollziehbar", "comprehensible / understandable"),
    ("36. Psychologie (erweitert)", "glaubwürdig", "credible"),
    ("36. Psychologie (erweitert)", "überfordert", "overwhelmed"),
    ("36. Psychologie (erweitert)", "reflektieren", "to reflect"),
    ("36. Psychologie (erweitert)", "sich identifizieren mit", "to identify with"),
    ("36. Psychologie (erweitert)", "sich anpassen", "to adapt / conform"),
    # ── 37. C1 Alltag & Präzision ──
    ("37. C1 Alltag & Präzision", "heutzutage", "nowadays"),
    ("37. C1 Alltag & Präzision", "in der heutigen Zeit", "in today's world"),
    ("37. C1 Alltag & Präzision", "vor kurzem", "recently"),
    ("37. C1 Alltag & Präzision", "in jüngster Zeit", "in recent times"),
    ("37. C1 Alltag & Präzision", "geschehen", "to happen / occur"),
    ("37. C1 Alltag & Präzision", "sich ereignen", "to occur / take place"),
    ("37. C1 Alltag & Präzision", "erscheinen", "to appear / seem"),
    ("37. C1 Alltag & Präzision", "wagen", "to dare / venture"),
    ("37. C1 Alltag & Präzision", "überqueren", "to cross"),
    ("37. C1 Alltag & Präzision", "umsonst", "in vain / for free"),
    ("37. C1 Alltag & Präzision", "der Eindruck", "impression"),
    ("37. C1 Alltag & Präzision", "das Vertrauen", "trust"),
    ("37. C1 Alltag & Präzision", "die Verantwortung", "responsibility"),
    ("37. C1 Alltag & Präzision", "die Voraussetzung", "prerequisite"),
    ("37. C1 Alltag & Präzision", "die Behauptung", "assertion / claim"),
    ("37. C1 Alltag & Präzision", "die Auseinandersetzung", "confrontation / debate"),
    ("37. C1 Alltag & Präzision", "die Fragestellung", "issue / research question"),
    ("37. C1 Alltag & Präzision", "die Betrachtungsweise", "perspective / point of view"),
    ("37. C1 Alltag & Präzision", "das Vorgehen", "procedure / approach"),
    ("37. C1 Alltag & Präzision", "die Erkenntnis", "insight / finding"),
    ("37. C1 Alltag & Präzision", "die Einschränkung", "limitation / restriction"),
    ("37. C1 Alltag & Präzision", "die Beurteilung", "assessment / evaluation"),
    ("37. C1 Alltag & Präzision", "seltsam", "strange"),
    ("37. C1 Alltag & Präzision", "vernünftig", "reasonable / sensible"),
    ("37. C1 Alltag & Präzision", "bedenklich", "questionable / worrying"),
    ("37. C1 Alltag & Präzision", "umfassend", "comprehensive"),
    ("37. C1 Alltag & Präzision", "ausführlich", "detailed / thorough"),
    ("37. C1 Alltag & Präzision", "gegenwärtig", "current / present"),
    ("37. C1 Alltag & Präzision", "hervorragend", "outstanding"),
    ("37. C1 Alltag & Präzision", "zuverlässig", "reliable"),
    ("37. C1 Alltag & Präzision", "überschaubar", "manageable / clear"),
    ("37. C1 Alltag & Präzision", "vage", "vague"),
    ("37. C1 Alltag & Präzision", "nachdrücklich", "emphatically / forcefully"),
    ("37. C1 Alltag & Präzision", "bedeutend", "significant"),
    ("37. C1 Alltag & Präzision", "anstreben", "to strive for"),
    ("37. C1 Alltag & Präzision", "beitragen zu", "to contribute to"),
    ("37. C1 Alltag & Präzision", "erfordern", "to require"),
    ("37. C1 Alltag & Präzision", "erleichtern", "to facilitate / make easier"),
    ("37. C1 Alltag & Präzision", "gestalten", "to shape / design"),
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    seen: set[tuple[str, str]] = set()
    rows: list[tuple[str, str, str]] = []
    for section, german, english in ENTRIES:
        key = (german.strip().lower(), section)
        if key in seen:
            continue
        seen.add(key)
        rows.append((section, german.strip(), english.strip()))

    with OUT.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["section", "german", "english"])
        writer.writerows(rows)

    sections = sorted({r[0] for r in rows})
    print(f"Wrote {len(rows)} entries in {len(sections)} sections → {OUT}")
    for sec in sections:
        n = sum(1 for r in rows if r[0] == sec)
        print(f"  {sec}: {n}")


if __name__ == "__main__":
    main()
